# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tag_id', to='todolist.Tag'),
        ),
    ]
